"""Add region_code to branches

Revision ID: 8cd21161947d
Revises: 56ab5caed48c
Create Date: 2025-03-12 13:20:24.896818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd21161947d'
down_revision = '56ab5caed48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('region_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_branches_region_code'), 'branches', ['region_code'], unique=False)
    op.drop_constraint('sla_configs_installation_type_id_fkey', 'sla_configs', type_='foreignkey')
    op.drop_column('sla_configs', 'total_sla_days')
    op.drop_column('sla_configs', 'estimate_days')
    op.drop_column('sla_configs', 'installation_days')
    op.drop_column('sla_configs', 'installation_type_id')
    op.drop_column('sla_configs', 'meter_size_range')
    op.drop_column('sla_configs', 'pipe_length_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sla_configs', sa.Column('pipe_length_range', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sla_configs', sa.Column('meter_size_range', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sla_configs', sa.Column('installation_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sla_configs', sa.Column('installation_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sla_configs', sa.Column('estimate_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sla_configs', sa.Column('total_sla_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sla_configs_installation_type_id_fkey', 'sla_configs', 'installation_types', ['installation_type_id'], ['id'])
    op.drop_index(op.f('ix_branches_region_code'), table_name='branches')
    op.drop_column('branches', 'region_code')
    # ### end Alembic commands ### 