"""Initial migration

Revision ID: 92cf16ed0c95
Revises: b1e7fb3c1e99
Create Date: 2025-03-09 03:35:17.724435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cf16ed0c95'
down_revision = 'b1e7fb3c1e99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 