"""Initial migration

Revision ID: b1e7fb3c1e99
Revises: 
Create Date: 2025-03-09 03:23:16.292906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1e7fb3c1e99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_statuses_code'), 'installation_statuses', ['code'], unique=True)
    op.create_index(op.f('ix_installation_statuses_id'), 'installation_statuses', ['id'], unique=False)
    op.create_table('installation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_types_code'), 'installation_types', ['code'], unique=True)
    op.create_index(op.f('ix_installation_types_id'), 'installation_types', ['id'], unique=False)
    op.create_table('meter_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_sizes_code'), 'meter_sizes', ['code'], unique=True)
    op.create_index(op.f('ix_meter_sizes_id'), 'meter_sizes', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('receiver', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('ba_code', sa.String(length=20), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_sent'), 'notifications', ['is_sent'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('costcenter', sa.String(length=50), nullable=True),
    sa.Column('ba', sa.String(length=50), nullable=True),
    sa.Column('part', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('job_name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('div_name', sa.String(length=100), nullable=True),
    sa.Column('dep_name', sa.String(length=100), nullable=True),
    sa.Column('org_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('ba_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('oracle_org_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_ba_code'), 'branches', ['ba_code'], unique=True)
    op.create_index(op.f('ix_branches_branch_code'), 'branches', ['branch_code'], unique=True)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_region_id'), 'branches', ['region_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('notification_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('receiver', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_configs_id'), 'notification_configs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_configs_type'), 'notification_configs', ['type'], unique=False)
    op.create_table('sla_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('fee_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_configs_id'), 'sla_configs', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('id_card', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_branch_id'), 'customers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_original_id'), 'customers', ['original_id'], unique=True)
    op.create_table('pwa_notification_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('ba_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['notification_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pwa_notification_targets_ba_code'), 'pwa_notification_targets', ['ba_code'], unique=False)
    op.create_index(op.f('ix_pwa_notification_targets_config_id'), 'pwa_notification_targets', ['config_id'], unique=False)
    op.create_index(op.f('ix_pwa_notification_targets_id'), 'pwa_notification_targets', ['id'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=6), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('monthly_target', sa.Integer(), nullable=False),
    sa.Column('cumulative_target', sa.Integer(), nullable=False),
    sa.Column('new_customers_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month', 'branch_id', name='uix_target_year_month_branch')
    )
    op.create_index(op.f('ix_targets_branch_id'), 'targets', ['branch_id'], unique=False)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_year_month'), 'targets', ['year_month'], unique=False)
    op.create_table('installation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('installation_type_id', sa.Integer(), nullable=True),
    sa.Column('meter_size_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_date', sa.DateTime(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('installation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bill_no', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('original_req_id', sa.String(length=50), nullable=True),
    sa.Column('original_install_id', sa.String(length=50), nullable=True),
    sa.Column('working_days_to_estimate', sa.Integer(), nullable=True),
    sa.Column('working_days_to_payment', sa.Integer(), nullable=True),
    sa.Column('working_days_to_install', sa.Integer(), nullable=True),
    sa.Column('working_days_to_complete', sa.Integer(), nullable=True),
    sa.Column('is_exceed_sla', sa.Boolean(), nullable=True),
    sa.Column('exceed_sla_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['installation_type_id'], ['installation_types.id'], ),
    sa.ForeignKeyConstraint(['meter_size_id'], ['meter_sizes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['installation_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_requests_branch_id'), 'installation_requests', ['branch_id'], unique=False)
    op.create_index(op.f('ix_installation_requests_customer_id'), 'installation_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_installation_requests_id'), 'installation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_installation_requests_request_date'), 'installation_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_installation_requests_request_no'), 'installation_requests', ['request_no'], unique=True)
    op.create_index(op.f('ix_installation_requests_status_id'), 'installation_requests', ['status_id'], unique=False)
    op.create_table('installation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_date', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['installation_requests.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['installation_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_logs_id'), 'installation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_installation_logs_installation_id'), 'installation_logs', ['installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_logs_installation_id'), table_name='installation_logs')
    op.drop_index(op.f('ix_installation_logs_id'), table_name='installation_logs')
    op.drop_table('installation_logs')
    op.drop_index(op.f('ix_installation_requests_status_id'), table_name='installation_requests')
    op.drop_index(op.f('ix_installation_requests_request_no'), table_name='installation_requests')
    op.drop_index(op.f('ix_installation_requests_request_date'), table_name='installation_requests')
    op.drop_index(op.f('ix_installation_requests_id'), table_name='installation_requests')
    op.drop_index(op.f('ix_installation_requests_customer_id'), table_name='installation_requests')
    op.drop_index(op.f('ix_installation_requests_branch_id'), table_name='installation_requests')
    op.drop_table('installation_requests')
    op.drop_index(op.f('ix_targets_year_month'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_branch_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_pwa_notification_targets_id'), table_name='pwa_notification_targets')
    op.drop_index(op.f('ix_pwa_notification_targets_config_id'), table_name='pwa_notification_targets')
    op.drop_index(op.f('ix_pwa_notification_targets_ba_code'), table_name='pwa_notification_targets')
    op.drop_table('pwa_notification_targets')
    op.drop_index(op.f('ix_customers_original_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_branch_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_sla_configs_id'), table_name='sla_configs')
    op.drop_table('sla_configs')
    op.drop_index(op.f('ix_notification_configs_type'), table_name='notification_configs')
    op.drop_index(op.f('ix_notification_configs_id'), table_name='notification_configs')
    op.drop_table('notification_configs')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_branches_region_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_branch_code'), table_name='branches')
    op.drop_index(op.f('ix_branches_ba_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_sent'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_meter_sizes_id'), table_name='meter_sizes')
    op.drop_index(op.f('ix_meter_sizes_code'), table_name='meter_sizes')
    op.drop_table('meter_sizes')
    op.drop_index(op.f('ix_installation_types_id'), table_name='installation_types')
    op.drop_index(op.f('ix_installation_types_code'), table_name='installation_types')
    op.drop_table('installation_types')
    op.drop_index(op.f('ix_installation_statuses_id'), table_name='installation_statuses')
    op.drop_index(op.f('ix_installation_statuses_code'), table_name='installation_statuses')
    op.drop_table('installation_statuses')
    # ### end Alembic commands ### 