"""change_branch_id_to_branch_code

Revision ID: ded5fcdce8bd
Revises: d3935560e630
Create Date: 2025-03-10 15:59:44.715063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded5fcdce8bd'
down_revision = 'd3935560e630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('branch_code', sa.String(length=20), nullable=True))
    op.drop_index('ix_customers_branch_id', table_name='customers')
    op.create_index(op.f('ix_customers_branch_code'), 'customers', ['branch_code'], unique=False)
    op.drop_constraint('customers_branch_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'branches', ['branch_code'], ['ba_code'])
    op.drop_column('customers', 'branch_id')
    op.add_column('installation_requests', sa.Column('branch_code', sa.String(length=20), nullable=True))
    op.drop_index('ix_installation_requests_branch_id', table_name='installation_requests')
    op.create_index(op.f('ix_installation_requests_branch_code'), 'installation_requests', ['branch_code'], unique=False)
    op.drop_constraint('installation_requests_branch_id_fkey', 'installation_requests', type_='foreignkey')
    op.create_foreign_key(None, 'installation_requests', 'branches', ['branch_code'], ['ba_code'])
    op.drop_column('installation_requests', 'branch_id')
    op.add_column('targets', sa.Column('branch_code', sa.String(length=20), nullable=False))
    op.drop_constraint('unique_target', 'targets', type_='unique')
    op.create_unique_constraint('unique_target', 'targets', ['year', 'month', 'branch_code', 'installation_type_id'])
    op.drop_constraint('targets_branch_id_fkey', 'targets', type_='foreignkey')
    op.create_foreign_key(None, 'targets', 'branches', ['branch_code'], ['ba_code'])
    op.drop_column('targets', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.create_foreign_key('targets_branch_id_fkey', 'targets', 'branches', ['branch_id'], ['id'])
    op.drop_constraint('unique_target', 'targets', type_='unique')
    op.create_unique_constraint('unique_target', 'targets', ['year', 'month', 'branch_id', 'installation_type_id'])
    op.drop_column('targets', 'branch_code')
    op.add_column('installation_requests', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'installation_requests', type_='foreignkey')
    op.create_foreign_key('installation_requests_branch_id_fkey', 'installation_requests', 'branches', ['branch_id'], ['id'])
    op.drop_index(op.f('ix_installation_requests_branch_code'), table_name='installation_requests')
    op.create_index('ix_installation_requests_branch_id', 'installation_requests', ['branch_id'], unique=False)
    op.drop_column('installation_requests', 'branch_code')
    op.add_column('customers', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_branch_id_fkey', 'customers', 'branches', ['branch_id'], ['id'])
    op.drop_index(op.f('ix_customers_branch_code'), table_name='customers')
    op.create_index('ix_customers_branch_id', 'customers', ['branch_id'], unique=False)
    op.drop_column('customers', 'branch_code')
    # ### end Alembic commands ### 